name: Update Premier League Standings
on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight
  workflow_dispatch:      # Allows you to run it manually for testing

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch API Data
        run: |
          curl -H "X-Auth-Token: ${{ secrets.VITE_FOOTBALL_API_KEY }}" \
          https://api.football-data.org/v4/competitions/PL/standings \
          -o public/standings.json

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add public/standings.json
          git commit -m "data: periodic standings update" || exit 0
          git push